name: dev
recipe: drupal8
config:
  webroot: .

services:
   node:
      type: node:6.10
      run:
        - "cd $LANDO_MOUNT && npm install"
        - "cd $LANDO_MOUNT && gulp"
      globals:
        gulp-cli: "latest"

tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
